### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Noorui12** [ayaanzhaque/MultiMix#1]
I am getting this error
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-41-d472fa42986e> in <module>()
      5 optimizer_ft = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=1e-4)
      6 exp_lr_scheduler = lr_scheduler.StepLR(optimizer_ft, step_size=8, gamma=0.1)
----> 7 model = train_model(model, optimizer_ft, exp_lr_scheduler, num_epochs = epochs)

<ipython-input-30-96e0a5c061df> in train_model(model, optimizer, scheduler, num_epochs)
    345 
    346             print_metrics(metrics, epoch_samples, phase)
--> 347             epoch_loss = metrics['loss'] / epoch_samples
    348 
    349             if phase == 'train':

ZeroDivisionError: float division by zero

Link to colab notebook: https://drive.google.com/file/d/1dLpkK1ab1DdUWMey_L8U9VKoGmYmS2A1/view?usp=sharing

**Comment by ayaanzhaque** [comment]
Hello,
This is because the epoch_samples are 0. I believe this is because your data loader does not have any actual data. Are you providing it with the correct dataset?
